# Generated by Django 4.2.20 on 2025-09-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXPIRYFY', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_no', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='rack_images/')),
            ],
        ),
    ]
